serial: 
	g++ -o w7-serial -std=c++11 w7.serial.cpp
semi-serial: 
	g++ -o w7-semi-serial -std=c++11 w7.semi-serial.cpp
cilk:
	g++ -o w7-cilk -std=c++11 -fcilkplus w7.parallel.cpp
semi-cilk:
	g++ -o w7-semi-cilk -std=c++11 -fcilkplus w7.semi-parallel.cpp

