all:
	g++ -I BalancedTree -std=c++11 -o w3 -fopenmp -O2 w3.main.cpp
balanced:
	g++ -I BalancedTree -std=c++11 -o w3 -fopenmp -O2 w3.main.cpp
spmd:
	g++ -I ThreeStepSPMD -std=c++11 -o w3 -fopenmp -O2 w3.main.cpp
ws:
	g++ -I ThreeStepWorkSharing -std=c++11 -o w3 -fopenmp -Ofast w3.main.cpp
serial:
	g++ -I TiledSerial -std=c++11 -o w3 -fopenmp -O2 w3.main.cpp