all:
	g++ -std=c++11 -o w3 -fopenmp -Ofast BalancedTree/w3.main.cpp
balanced:
	g++ -std=c++11 -o w3 -fopenmp -Ofast BalancedTree/w3.main.cpp
spmd:
	g++ -std=c++11 -o w3 -fopenmp -Ofast ThreeStepSPMD/w3.main.cpp
ws:
	g++ -std=c++11 -o w3 -fopenmp -Ofast ThreeStepWorkSharing/w3.main.cpp
serial:
	g++ -std=c++11 -o w3 -fopenmp  -Ofast TiledSerial/w3.main.cpp