all:
	g++ -I BalancedTree -std=c++11 -o w3 -fopenmp -O2 BalancedTree/w3.main.cpp
balanced:
	g++ -I BalancedTree -std=c++11 -o w3 -fopenmp -O2 BalancedTree/w3.main.cpp
spmd:
	g++ -I Three-StepSPMD -std=c++11 -o w3 -fopenmp -O2 Three-StepSPMD/w3.main.cpp
ws:
	g++ -I Three-StepWorkSharing -std=c++11 -o w3 -fopenmp -Ofast Three-StepWorkSharing/w3.main.cpp
serial:
	g++ -I TiledSerial -std=c++11 -o w3 -fopenmp -O2 TiledSerial/w3.main.cpp